variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: Microservicio que envía al cliente un SMS con una liga corta que le permitirá continuar posteriormente con su solicitud de tarjeta de crédito.
server:
  port: 7793
spring:
  config:
    name: cc-apps-sms-folio-send-ms
  application:
    name: cc-apps-sms-folio-send-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
    
logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.ccappssmsfoliosendms: DEBUG    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
            
encryption: 
    ivBytes: YNpQKRzrA6DkNxCgQd5YIQ==
    keySize: 256
    passWord: '^The_chance_wont_come_again_And_dont_speak_too_soon_For_the_wheel_is_still_in_spin_And_there_is_no_telling_who_That_its_naming_For_the_loser_now_Will_be_later_to_win_For_the_times_they_are_a-changing^'
    pswdIterations: 65536
    salt: '^S4l4t#f-$24d08m1988yt4mp1c0$02s12dds1212212@$@4&~#%^$*'
  
  