variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: Microservicio de Custumer NC
server:
  port: 7609
spring:
  config:
    name: cc-apps-customer-nc-ms
  application:
    name: cc-apps-customer-nc-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000