variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: Microservicio regresa información de la dirección en base al nombre de la colonia y el ID del estado.
server:
  port: 7792
spring:
  config:
    name: cc-apps-bureau-query-ms
  application:
    name: cc-apps-bureau-query-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.ccappsbureauqueryms: DEBUG

messages:
    empty: Field may not be empty
    gender: Only F, M
    invalid: Invalid data
    invalidMail: Invalid email
    lAndPhoneNumber: 'Lada more phone is not equal to 10:'
    leter: Only letters are allowed
    leterAndSpace: Only letters and spaces are allowed
    leterNumbersAndSpace: Only letters, numbers and spaces are allowed
    noData: No data has been provided to process
    numbersOnly: Only numbers are allowed
    requiredField: Field is required
    trueFalse: Only true, false
    validRange: 'The valid range is: '
    wrongData: Incorrect data
    zeroOne: 0 | 1
    invalidFormat: 'Invalid Format:'    
    invalidRange: 'The range is:'
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000