variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: Microservicio de Adress por CP
server:
  port: 7787
spring:
  config:
    name: cc-apps-address-ms
  application:
    name: cc-apps-address-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000