variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: Bureau Microservice
server:
  port: 7794
spring:
  config:
    name: cc-bureau-accreditation-ms
  application:
    name: cc-bureau-accreditation-ms

logging:
  level:
    com.banamex.portal: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

#UAT            
addresses:
    endPointBureau: https://b72780-vip.nam.nsroot.net:13081
    endPointCatalogos: 0.0.0.0
    endPointCi: https://B61646-vip.nam.nsroot.net:46600 
    endPointCiAdapter: 0.0.0.0
    endPointDefault: 0.0.0.0            