variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: Microservicio hace un subllamado, url no expuesta para agregar datos de un cliente a una tarjeta de credito
server:
  port: 7796
spring:
  config:
    name: cc-ci-card-add-ms
  application:
    name: cc-ci-card-add-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
    
logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.cccicardaddms: DEBUG
    
messages:
    empty: Field may not be empty
    gender: Only F, M
    invalid: Invalid data
    invalidMail: Invalid email
    lAndPhoneNumber: 'Lada more phone is not equal to 10:'
    leter: Only letters are allowed
    leterAndSpace: Only letters and spaces are allowed
    leterNumbersAndSpace: Only letters, numbers and spaces are allowed
    noData: No data has been provided to process
    numbersOnly: Only numbers are allowed
    requiredField: Field is required
    trueFalse: Only true, false
    validRange: 'The valid range is: '
    wrongData: Incorrect data
    zeroOne: 0 | 1
    invalidFormat: 'Invalid Format:'    
    invalidRange: 'The range is:'    
    
feign:
    url: https://www.mobileuat.banamex.com    
    
addresses:
    endPointBureau: http://192.168.10.166:8081/cc-credit-origination-ws/CreditOriginationService
    endPointCatalogos: http://192.168.10.166:8081/cc-credit-origination-ws/CreditOriginationService
    endPointCi: http://adlenovot430:8081/cc-app14-ws/App14Service
    endPointCiAdapter: '?'
    endPointDefault: 0.0.0.0        
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000