variables:
  eureka:
    host: localhost
 #   host: service-registry-host
    port: 8761

info:
  component: Microservicio Servicio que regresa información de la dirección en base al nombre de la colonia y el ID del estado..

server:
  port: 0
#  port: 7806

spring:
  config:
    name: cc-c080-ms
  application:
    name: cc-c080-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:{random.value}}
    preferIpAddress: true
    
logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.ccs080ms: DEBUG  
    
feign:
  url: https://www.mobileuat.banamex.com
  #url: http://192.168.11.58:7778
  #url: http://150.110.186.56:50719   
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000    
