variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: Microservicio que obtiene el listado de tarjetas de un determinado cliente utilizando dos opciones el número de cliente o el nombre y la fecha de nacimiento, siendo el número de cliente prioritario si se proporcionan todos los datos.
server:
  port: 7795
spring:
  config:
    name: cc-ci-cards-ms
  application:
    name: cc-ci-cards-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
    
logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.cccicardsms: DEBUG
    
feign:
    url: https://www.mobileuat.banamex.com
    #url: http://192.168.11.58:7778

addresses:
    endPointBureau: http://192.168.10.166:8081/cc-credit-origination-ws/CreditOriginationService
    endPointCatalogos: http://192.168.10.166:8081/cc-credit-origination-ws/CreditOriginationService
    endPointCi: http://adlenovot430:8081/cc-app15-ws/App15Service
    #endPointCi: http://169.178.114.161:5999/SvcImpl/common/MX/application/v3_2_MX_15/SOAPEndpoint/ApplicationService.serviceagent/OpEndpointHTTP
    endPointCiAdapter: '?'
    endPointDefault: 0.0.0.0        
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000