variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: S016 Client Microservice
server:
  port: 7798
spring:
  config:
    name: cc-s016-client-ms
  application:
    name: cc-s016-client-ms

logging:
  level:
    com.banamex.portal: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

feign:
    name: S016Back
    #url: http://150.110.186.56:50719
    #url: http://localhost:8762
    url:  https://www.mobileuat.banamex.com