variables:
  eureka:
    host: localhost
#    host: service-registry-host
    port: 8761

info:
  component: Find offers to clients by number client or folio

server:
  port: 7800

spring:
  config:
    name: cc-xsell-offers-ms
  application:
    name: cc-xsell-offers-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
    
logging:
    level:
        org.springframework.web: INFO
        com.banamex.portal.microservice.ccxselloffersms: DEBUG
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
