variables:
  eureka:
#    host: service-registry-host
    host: localhost
    port: 8761
info:
  component: Crossell domain operations
server:
  port: 7803
spring:
  config:
    name: cc-xsell-domains-ms
  application:
    name: cc-xsell-domains-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
    
logging:
    level:
        com.banamex.portal.microservice.ccxselldomainscreatems: DEBUG
        org.springframework.web: INFO    

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
      
