variables:
  eureka:
    #host: localhost
    host: service-registry-host
    port: 8761
info:
  component: Microservicio para consulta de metales
#server:
  #port: 7745
spring:
  config:
    name: ef-metals-ms
  application:
    name: ef-metals-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true

logging:
    level:
        org.springframework.web: INFO
        com.banamex.portal.microservice.efmetalsms: DEBUG    

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000