variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: Microservicio de Tiempos de espera estimados en sucursal (ewt)
server:
  port: 7720
spring:
  config:
    name: ewt-ms
  application:
    name: ewt-ms
  cloud:
    services:
      registrationMethod: route
security:
  basic:
    enabled: false  
logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.ewtms: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
