variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
  redis:
    #host: localhost
    #host: redis-host
    host: 192.168.10.205
    port: 6379
  #  configuration:
  #       secure:
  #            true
    

info:
  component: PortalMicroservices gateway ms (based on Netflix Zuul)

server:
  port: 7690

security:
  sessions: ALWAYS

spring:
  config:
    name: gateway-ms
  application:
    name: gateway-ms
  session:
    store-type: redis
  redis:
    host: ${variables.redis.host}
    port: ${variables.redis.port}
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

zuul:
  routes:
    dashboardEureka:
      path: /eureka/**
      url: http://${variables.eureka.host}:${variables.eureka.port}/

    # EWT
    ewt-ms:
      path: /ewt/**
      serviceId: ewt-ms

    # EF
    ef-dollar-ms:
      path: /ef-dollar/**
      serviceId: ef-dollar-ms
    ef-currencies-ms:
      path: /ef-currencies/**
      serviceId: ef-currencies-ms
    ef-metals-ms:
      path: /ef-metals/**
      serviceId: ef-metals-ms

    # VT
    vt-ddl-ms:
      path: /vt-ddl/**
      serviceId: vt-ddl-ms
    vt-dml-ms:
      path: /vt-dml/**
      serviceId: vt-dml-ms
    vt-query-ms:
      path: /vt-query/**
      serviceId: vt-query-ms

    # CC
    cc-apps-customer-ms:
      path: /cc-apps-customer/**
      serviceId: cc-apps-customer-ms
    cc-apps-msg-encrypt-ms:
      path: /cc-apps-msg-encrypt/**
      serviceId: cc-apps-msg-encrypt-ms
    cc-apps-datacredit-ms:
      path: /cc-apps-datacredit/**
      serviceId: cc-apps-datacredit-ms
    cc-apps-datacredit-otp-ms:
      path: /cc-apps-datacredit-otp/**
      serviceId: cc-apps-datacredit-otp-ms
    cc-apps-write-ms:
      path: /cc-apps-write/**
      serviceId: cc-apps-write-ms
    cc-apps-address-ms:
      path: /cc-apps-address/**
      serviceId: cc-apps-address-ms
    cc-apps-status-ms:
      path: /cc-apps-status/**
      serviceId: cc-apps-status-ms
    cc-apps-process-ms:
      path: /cc-apps-process/**
      serviceId: cc-apps-process-ms
    cc-apps-bureau-query-ms:
      path: /cc-apps-bureau-query/**
      serviceId: cc-apps-bureau-query-ms
    cc-apps-sms-folio-send-ms:
      path: /cc-apps-sms-folio-send/**
      serviceId: cc-apps-sms-folio-send-ms
    cc-bureau-ms:
      path: /cc-bureau/**
      serviceId: cc-bureau-ms
    cc-ci-cards-ms:
      path: /cc-ci-cards/**
      serviceId: cc-ci-cards-ms
    cc-ci-card-add-ms:
      path: /cc-ci-card-add/**
      serviceId: cc-ci-card-add-ms
    cc-ci-status-ms:
      path: /cc-ci-status/**
      serviceId: cc-ci-status-ms
    cc-s016-client-ms:
      path: /cc-s016-client/**
      serviceId: cc-s016-client-ms
    cc-s080-ms:
      path: /cc-s080/**
      serviceId: cc-s080-ms

    # CC XSell
    cc-xsell-offers-ms:
      path: /cc-xsell-offers/**
      serviceId: cc-xsell-offers-ms
    cc-xsell-offers-upload-ms:
      path: /cc-xsell-offers-upload/**
      serviceId: cc-xsell-offers-upload-ms
    cc-xsell-domains-ms:
      path: /cc-xsell-domains/**
      serviceId: cc-xsell-domains-ms

    # Portal users
    portal-users-ms:
      path: /portal-users/**
      serviceId: portal-users-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true

logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.gatewayms: DEBUG

# 3 minutos de timeout de respuesta y 5 segundos para tratar de conectarse
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 180000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 180000
