variables:
  eureka:
    #host: localhost
    host: service-registry-host
    port: 8761
info:
  component: Microservice for updating portal users
#server:
#  port: 7703
spring:
  config:
    name: users-update-ms
  application:
    name: users-update-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.userscreatems: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000