variables:
  eureka:
    #host: service-registry-host
    host: localhost
    port: 8761

info:
  component: Microservicio de operaciones ddl en tablas virtuales

server:
  port: 7761

spring:
  config:
    name: vt-ddl-ms
  application:
    name: vt-ddl-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000    
logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.vtddlms: DEBUG
