variables:
  eureka:
    host: localhost
    #host: service-registry-host
    port: 8761
info:
  component: Microservicio de Base de Datos
server:
  port: 7708
spring:
  config:
    name: vt-database-ms
  application:
    name: vt-database-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  30000
            
            
logging:
  level:
    org.springframework.web: INFO
    com.banamex.portal.microservice.vtdatabasems: DEBUG

db.driverClass: oracle.jdbc.OracleDriver
db.jdbcUrl: jdbc:oracle:thin:@34.230.196.141:1521:xe
db.user: VT
db.password: password

c3p0.minPoolSize: 4
c3p0.maxPoolSize: 20
c3p0.acquireIncrement: 2
c3p0.breakAfterAcquireFailure: false
c3p0.maxIdleTime: 10